In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,2,3] , [3,4,5] , [5,6,7]]) 
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [3]:
aa = a@a
aa

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])

In [4]:
a1 = np.dot(a , a)
a1

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])

In [5]:
np.multiply(a,a)

array([[ 1,  4,  9],
       [ 9, 16, 25],
       [25, 36, 49]])

In [6]:
np.prod(a)

75600

In [7]:
#broad casting
myArray = np.array([1,2,3])
myArray +5

array([6, 7, 8])

In [8]:
g = np.ones((3,1))
print(myArray)
print(g)
myArray + g    

[1 2 3]
[[1.]
 [1.]
 [1.]]


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [9]:
np.sum(a)

36

In [10]:
np.cumsum(a , axis = 0) #for row

array([[ 1,  2,  3],
       [ 4,  6,  8],
       [ 9, 12, 15]], dtype=int32)

In [11]:
np.cumsum(a , axis = 1) #for culmn

array([[ 1,  3,  6],
       [ 3,  7, 12],
       [ 5, 11, 18]], dtype=int32)

In [12]:
np.subtract(myArray , g)

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [13]:
np.divide(myArray , g)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [14]:
np.floor_divide(myArray , g)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [15]:
np.math.sqrt(2)

1.4142135623730951

In [16]:
np.math.nan

nan

In [17]:
np.math.inf

inf

In [18]:
np.random.uniform(1,5 , (3,3))

array([[1.08899139, 1.40450645, 2.44816127],
       [2.56152922, 4.39025389, 2.69537856],
       [1.77392605, 4.01595507, 3.33736691]])

In [19]:
np.random.standard_normal((1,2))

array([[ 0.90780192, -1.78770575]])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
my_mask = a>2
a[my_mask]

array([3, 3, 4, 5, 5, 6, 7])

In [23]:
my_mask1 = np.logical_and(a>1 , a<3)
a[my_mask1]

array([2])

In [24]:
np.size(a)

9

In [25]:
np.shape(a)

(3, 3)

In [26]:
b = np.array([[10,2] , [8,9] , [7,6]])
b

array([[10,  2],
       [ 8,  9],
       [ 7,  6]])

In [27]:
np.union1d(a,b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.interesect1d(a,b)

AttributeError: module 'numpy' has no attribute 'interesect1d'

In [29]:
np.mean(a)

4.0

In [30]:
np.var(a)

3.3333333333333335

In [31]:
np.median(a)

4.0

In [32]:
np.std(a)

1.8257418583505538

In [33]:
x = np.array([1,2,4])

In [34]:
np.polyval(x , 1)

7

In [35]:
np.polyder(x)

array([2, 2])

In [36]:
np.polyint(x)

array([0.33333333, 1.        , 4.        , 0.        ])

In [37]:
mySeries = pd.Series([1,2,3,4,5] , index = ["row1","row2","row3","row4","row5"])
mySeries

row1    1
row2    2
row3    3
row4    4
row5    5
dtype: int64

In [38]:
mySeries.values

array([1, 2, 3, 4, 5], dtype=int64)

In [39]:
mySeries.index

Index(['row1', 'row2', 'row3', 'row4', 'row5'], dtype='object')

In [40]:
mySeries.row2

2

In [41]:
mySeries.rename({'row1' : 'edited'})

edited    1
row2      2
row3      3
row4      4
row5      5
dtype: int64

In [42]:
d = np.array([[1,2,3] , [4,5,6] , [7,8,9] , [10,11,12] , [13,14,15]]) #data form satri
myDataFrame = pd.DataFrame(d , index = ['row1' , 'row2' , 'row3' , 'row4' , 'row5'] , columns = ['col1' , 'col2' , 'col3'])
myDataFrame

col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9
row4    10    11    12
row5    13    14    15

In [43]:
c = {'col1' : [1,4,7,10,13] , 'col2' : [2,5,8,11,14] , "col3" :[3,6,9,12,15]}
myDataFrame = pd.DataFrame(c , index = ['row1' , 'row2' , 'row3' , 'row4' , 'row5'] , columns = ['col1' , 'col2' , 'col3'])
myDataFrame

col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9
row4    10    11    12
row5    13    14    15

In [44]:
myDataFrame.index

Index(['row1', 'row2', 'row3', 'row4', 'row5'], dtype='object')

In [45]:
myDataFrame.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [46]:
myDataFrame.values

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]], dtype=int64)

In [47]:
myDataFrame.loc['row3']['col1']

7

In [48]:
myDataFrame.iloc[2][0]

7

In [49]:
myDataFrame['col4'] = [23,22,24,89,88]
myDataFrame

col1  col2  col3  col4
row1     1     2     3    23
row2     4     5     6    22
row3     7     8     9    24
row4    10    11    12    89
row5    13    14    15    88

In [50]:
myDataFrame.reset_index(drop =True , inplace = True)
myDataFrame

col1  col2  col3  col4
0     1     2     3    23
1     4     5     6    22
2     7     8     9    24
3    10    11    12    89
4    13    14    15    88

In [51]:
myDataFrame.rename(columns = {'col4' : "edited"} , inplace = True)
myDataFrame

col1  col2  col3  edited
0     1     2     3      23
1     4     5     6      22
2     7     8     9      24
3    10    11    12      89
4    13    14    15      88

In [52]:
 #myDataFrame.col1 = ['{: .2f}'.format(x) for x in myDataFrame.iloc[ : , 0]]
myDataFrame

col1  col2  col3  edited
0     1     2     3      23
1     4     5     6      22
2     7     8     9      24
3    10    11    12      89
4    13    14    15      88

In [53]:
myDataFrame.col1 = ['{ : .f}'.format(x) for x in myDataFrame.iloc[ : , 0]]
myDataFrame

KeyError: ' '

In [54]:
myDataFrame['edited'] = ['{:.2f}'.format(x) for x in myDataFrame.iloc[: , 0]]
myDataFrame

col1  col2  col3 edited
0     1     2     3   1.00
1     4     5     6   4.00
2     7     8     9   7.00
3    10    11    12  10.00
4    13    14    15  13.00

In [55]:
myDataFrame['col3'] = myDataFrame['col3'].apply(lambda x : '{:.2f}'.format(x))
myDataFrame

col1  col2   col3 edited
0     1     2   3.00   1.00
1     4     5   6.00   4.00
2     7     8   9.00   7.00
3    10    11  12.00  10.00
4    13    14  15.00  13.00

In [59]:
z=myDataFrame.sort_index(axis =1 , ascending = False)
z

edited   col3  col2  col1
0   1.00   3.00     2     1
1   4.00   6.00     5     4
2   7.00   9.00     8     7
3  10.00  12.00    11    10
4  13.00  15.00    14    13

In [64]:
j=myDataFrame.sort_values(by = 'col3' , ascending = False)
j


col1  col2   col3 edited
2     7     8   9.00   7.00
1     4     5   6.00   4.00
0     1     2   3.00   1.00
4    13    14  15.00  13.00
3    10    11  12.00  10.00

In [65]:
myDataFrame.head(2)

col1  col2  col3 edited
0     1     2  3.00   1.00
1     4     5  6.00   4.00

In [66]:
myDataFrame.tail(2)

col1  col2   col3 edited
3    10    11  12.00  10.00
4    13    14  15.00  13.00